# Simple workflow for deploying static content to GitHub Pages
name: Deploy birthdays

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["release"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'cristianalarcongonzalez'
        git config --global user.email 'cristianalarcon109@gmail.com'

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.T2PPS2 }}
          publish_dir: .
     
